# Generated by Django 4.0.4 on 2022-05-16 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_Agrege_Cloudinary_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='categoria'),
        ),
    ]
